import Link from "next/link";
import {
  ArrowRight,
  Layers,
  Package,
  Camera,
  Coins,
  CheckCircle2,
} from "lucide-react";

export const metadata = {
  title: "How it works — Source[Archive] for brands",
  description: "A walkthrough of running a collection in Source[Archive], from kickoff through delivered production.",
};

const STEPS = [
  {
    n: "01",
    icon: <Layers size={18} />,
    title: "Create a collection",
    body:
      "Give it a name, a season, a base currency, and a target margin. Set your key dates — kickoff, sample deadline, ex-factory, launch. The timeline lines up around them.",
    detail:
      "Everything downstream anchors to these dates. Miss ex-factory, and the launch marker on the collection Gantt turns red across every view.",
  },
  {
    n: "02",
    icon: <Package size={18} />,
    title: "Quick-add products",
    body:
      "Name, category — done. You get a style code auto-generated by category prefix. Fill in the rest as it happens: colorways, sizes, target quantity, spec notes.",
    detail:
      "The style code is unique per workspace and format-locked to your category taxonomy: DNM-004, LJK-002, ACT-011.",
  },
  {
    n: "03",
    icon: <Camera size={18} />,
    title: "Run sample rounds",
    body:
      "Every proto lives as a round on its product. Requested, shipped, received — status, tracking, ETA, photos, revision notes. Feedback threads scoped to that round.",
    detail:
      "Round 3 approved doesn't collapse Rounds 1 and 2. Your factory sees the whole trail so nothing regresses to a previous version.",
  },
  {
    n: "04",
    icon: <Coins size={18} />,
    title: "Cost it. Price it. Watch margins.",
    body:
      "Enter costs in the factory's currency — CNY, EUR, whatever. Split by fabric, trims, labour, freight. Sale prices in your base currency. Live margin preview per product.",
    detail:
      "Set FX rates once per collection; costing rolls up per category and per collection. Products under target margin get flagged.",
  },
  {
    n: "05",
    icon: <CheckCircle2 size={18} />,
    title: "Move the pipeline",
    body:
      "Drag styles across the kanban: Concept → Design → Tech Pack → Sampling → Approved → Production → Delivered. Guardrails catch skipped approvals.",
    detail:
      "Timeline, kanban, and Gallery are the same data. Toggle views. Everything stays in sync.",
  },
];

export default function HowItWorksPage() {
  return (
    <div>
      <section className="max-w-4xl mx-auto px-6 pt-20 pb-14 text-center">
        <p className="text-[11px] uppercase tracking-widest text-[var(--sa-text-tertiary)] mb-3">The walkthrough</p>
        <h1 className="font-serif text-[42px] sm:text-[52px] leading-[1.05] tracking-tight">
          Kickoff to delivered — the five moves.
        </h1>
        <p className="mt-5 text-[15px] text-[var(--sa-text-secondary)] max-w-2xl mx-auto">
          A collection in Source[Archive] follows the same rhythm your studio already runs on.
          Here's what each step looks like in the app.
        </p>
      </section>

      <section className="max-w-4xl mx-auto px-6 pb-24">
        <ol className="space-y-14">
          {STEPS.map((s) => (
            <li key={s.n} className="grid grid-cols-1 md:grid-cols-[80px_1fr] gap-6">
              <div>
                <div className="text-[42px] font-serif text-[var(--sa-text-tertiary)] leading-none">{s.n}</div>
                <div className="mt-3 inline-flex h-9 w-9 items-center justify-center rounded-full bg-[var(--sa-text-primary)] text-[var(--sa-window)]">
                  {s.icon}
                </div>
              </div>
              <div>
                <h2 className="text-[24px] font-serif font-semibold">{s.title}</h2>
                <p className="mt-2 text-[14px] text-[var(--sa-text-secondary)] leading-relaxed">{s.body}</p>
                <p className="mt-3 text-[12.5px] text-[var(--sa-text-tertiary)] italic border-l-2 border-[var(--sa-border)] pl-3">
                  {s.detail}
                </p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section className="bg-[var(--sa-window)] border-y border-[var(--sa-border)]">
        <div className="max-w-3xl mx-auto px-6 py-16 text-center">
          <h2 className="font-serif text-[28px] sm:text-[36px] tracking-tight">See it with your own collection.</h2>
          <p className="mt-3 text-[13px] text-[var(--sa-text-secondary)]">
            The 14-day trial gives you every feature. Cancel any time, keep your data if you upgrade.
          </p>
          <div className="mt-7 flex flex-col sm:flex-row gap-2 items-center justify-center">
            <Link
              href="/sign-up"
              className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--sa-text-primary)] px-5 py-3 text-[13px] font-medium text-[var(--sa-window)] hover:opacity-90"
            >
              Start free trial <ArrowRight size={13} />
            </Link>
            <Link
              href="/for-brands/pricing"
              className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--sa-border)] px-5 py-3 text-[13px] font-medium text-[var(--sa-text-primary)] hover:bg-[var(--sa-hover)]"
            >
              See pricing
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
